input {
  tcp {
    port => 5000
    codec => json
  }

  beats {
    port => 5044
  }
}

filter {
  if [type] == "ceph" {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:loglevel} %{GREEDYDATA:message}" }
    }

    date {
      match => [ "timestamp", "ISO8601" ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "ceph-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
